apiVersion: v1
kind: Secret
metadata:
  name: secret-key
data:
  {{- if .Release.IsInstall }}
  secret-key: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  secret-key:  {{ index (lookup "v1" "Secret" .Release.Namespace "secret-key").data "secret-key" }}
  {{ end }}